import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { TRPCReactProvider } from '@/trpc/client';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Starter Kit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body className={`${inter.className}  antialiased`}>
          {children}
          <Toaster position="top-right" richColors />
        </body>
      </html>
    </TRPCReactProvider>
  );
}
